
fn do_initialize(_this: &HacashMinter, db: &mut dyn State) -> Rerr {
    
	let addr1 = Address::from_readable("12vi7DEZjh6KrK5PVmmqSgvuJPCsZMmpfi").unwrap();
	let addr2 = Address::from_readable("1LsQLqkd8FQDh3R7ZhxC5fndNf92WfhM19").unwrap();
	let addr3 = Address::from_readable("1NUgKsTgM6vQ5nxFHGz1C4METaYTPgiihh").unwrap();
	let amt1 = Amount::small(1, 244);
	let amt2 = Amount::small(12, 244);
    let bls1 = Balance::hac(amt1);
    let bls2 = Balance::hac(amt2);
    let mut state = CoreState::wrap(db);
    state.balance_set(&addr1, &bls2);
    state.balance_set(&addr2, &bls1);
    state.balance_set(&addr3, &bls1);

    // just for test develop
    #[cfg(debug_assertions)] 
    if _this.cnf.test_coin {
        let tadr = "1MzNY1oA3kfgYi75zquj3SRUPYztzXHzK9";
        println!("[Debug Mint] {} => 1000000HAC + 5000BTC + 360HACD", tadr);
	    let addr = Address::from_readable(tadr).unwrap();
	    let amt = Amount::small(1, 254); // 1000000 HAC
        let mut bls = Balance::hac(amt); 
        bls.satoshi = Fold64::from(500000000000)?; // 500 BTC
        state.balance_set(&addr, &bls);
        test_add_360_diamonds(&mut state, &addr)?; // 360 HACD
    }

    // ok
    Ok(())
} 

#[allow(unused)]
fn test_add_360_diamonds(state: &mut CoreState, addr: &Address) -> Rerr {
    let stuff = "KKKKVA,HYXYHY,UETWNK,WYUKKZ,EYWTUK,VVYNHB,VUXZNT,UZENMV,NXKNEE,YSWNWT,IEWIVE,AAHKWY,VMKNWZ,BXKWUY,XNWWMH,EWUISY,UYASKU,NVNXIV,ENYEKZ,XTXBNH,BXMBEB,YZVIZH,ZUAWNA,NNXBAY,IWKAZB,XHBBAK,TBNNSZ,YNKZXT,HKTSZU,AUBIWE,AAZIIV,AVXSEU,MAXMAM,TINEAT,BVTXXE,WVEBIV,ZTBEVW,NBVAHU,VENNXZ,XBUKAI,WKHSSE,VTTXNN,UIEABX,AYSWXY,KMESEY,YBSTIK,ITXMNY,UEZAEI,YEZZNE,SMKBHM,WIAEVB,BNVKXE,SNHSYV,ZEAWTB,ZVTTAZ,WSWEKT,VXUUUU,MKZNIY,TXWSMZ,UZTVNS,BNMETT,UMVYYM,HBSKSW,HWYESI,SBAZYM,VEAHIA,XAZXIE,YTMIVT,EYXYWE,SYUKTN,VXAUHA,MVKXIN,WXWBTX,AYYIBN,TSYNXB,SNUVAY,XKTMNH,AKWEUM,XAXWIN,IZBSYY,YEBSSB,MUVMWB,TTHIWU,IWWBUT,ZYEHVM,ASHMBB,WYEMZB,WTEIYK,BYMVUM,VBYAYH,MVKSKB,EUZIXI,TXWWSV,USHBKI,MTUIUH,ZZSWSZ,MHSITK,UHTYNY,ITWTMK,ASHYMH,IXBZKV,TWNNKK,BHXATS,BSSEYK,VYISVM,MZKKEE,VUHNMM,WASXVM,VNTMST,XKSIZV,YEAHVI,STKYUH,BMMBKM,SWAEUM,VETHUI,HUZAKB,UKEMZN,KTHYEB,TATSBK,NUYEVN,VSXUYM,ANYSXS,NTBIMM,KWINAS,SBNVZY,ZHZXEU,XTZNWK,SHTMVB,TUUVZS,NBHBZH,XBEKSW,AIZSTX,YBBWSI,NKNKHW,ZVNBUW,YANUBA,TXHAIN,TEYWYW,HVVSTT,UZBVZX,IWTSSN,KUWVEV,UEVHAB,SBANWE,ZVVBWV,UWNYTX,SVUEBE,UKUTTT,KVWEKY,XWBZXU,BEXAMA,AUSATI,SIWNUS,MMTVYB,AVSWHH,SIXEWT,KYUXIW,XBNKST,KKVIAM,IXVEKA,AAWUST,ITHWMS,WZIIAV,YAZEAV,MNUBUN,ZWSKUA,AZEXKZ,MYIWUK,INIKBH,HTUBZZ,XVTXXU,HMISVX,EXTTMS,TMYXMB,VXABMN,ABUMYE,EUBWKE,SUNHUZ,WIYXHE,WNBWZE,KVMIHZ,KWWZTZ,NTUYKN,MMNNBW,VBKNVT,WBSZHH,UNKIXB,UXNKYB,WWZZEU,IWNEHI,WVWTVK,MVNXHK,HTWUNT,SVAYWZ,UZBAHT,UTVMXT,XVHSKI,WWZVVE,SMXHBZ,EIVIBZ,IASEIS,ZTBUYT,ISESBT,SIKSKZ,VEMXYE,THMTTM,ZBEKVB,BBNSSS,WYSSVN,KMIIAU,HHAUKY,HZXXUE,ANABXM,EHMZHW,IMHWXM,ETNEXV,ETIWZI,UVEBIZ,IVMEZX,NNSTTY,AIIMYK,WZATHM,USXTIW,MZKETN,VXEZZS,HUEYUM,IVIKAB,KAATMA,ABBSVB,EZSAZY,WVNHSS,NTUZME,WEZBVB,HNYTVH,MEKTEU,VUNMYZ,BYKTZW,XHKZWT,VXYXNH,VMIUWW,HVXKMI,ZNHEHB,MEEYEM,WHYKTS,ZXZTTZ,MSNAUS,HTWMZS,MNYMVE,ZYUSKN,AWVWYE,STTZZU,ZUHXSM,KEEEWY,KBEZYK,NSTVET,IWZEKT,ZSKEBW,XEZHUH,XMXZZS,USUEXI,SSAAXN,UEZUUM,XVEEWB,HHAZVW,NXESEI,HATIXV,ATZYXB,YNASUE,TITYTT,SNZVIZ,EBYWHA,ZUXXMN,BNYSUN,XETKUH,HHXVTT,TSUUSU,AIWZAT,XUWBSA,XXKUNV,XTMEAI,NKUMUS,HIXWHT,BHYNMM,SNYXZY,KUBHSV,XUNWBM,WSMEKK,MIZNAN,NZHMHB,KYEHKM,KAYATH,KWSKIT,AAWIVB,EUUKEI,IBWXBE,ESUSNZ,MSYTKX,UVAIXY,IZAYXE,XYATWY,VVBSSY,MTHMZI,IAHNHA,XEHAUB,HYBSZK,EKNBKN,NVEYUZ,XTTKST,NHXHIV,XYBSWK,USYHHA,XBBKBM,VIUKWY,ZYZMYS,MUVTNI,SMHUAW,NBTHKH,TIAVBU,TATUZE,EMWZTK,AAESWM,EYWUKM,YIHHTW,YNNYWV,IXWKSM,XAIIKN,XVMNVU,YIIXIB,AUSIXB,UWTXNN,ZBWAYI,HATUHA,AXIBNV,KNZBAH,KNWVUA,ZKHBYA,NBBSAH,UUKWHU,IYXIUZ,BMHSKK,SYXESV,HHSSUH,WTEABS,SIEVZX,HMMSZM,NBWBME,BNTKMA,AIMNMY,EVHBWE,XXKWYM,VTMHBN,SBZHBU,YSISAH,KSWMAT,NTZSAB,HTNXAZ,BWAKZS,NYBXAB,WUUVVB,YZXIXW";
    use protocol::operate::*;
    let diamonds = DiamondNameListMax60000::from_readable(stuff)?;
    let dias = diamonds.length() as u32;
    // add dia sto
    for one in diamonds.clone().into_iter() {
        state.diamond_set(&one, &DiamondSto{
            status: DIAMOND_STATUS_NORMAL,
            address: addr.clone(),
            ..DiamondSto::default()
        });
    }
    // add diamond belong
    diamond_owned_append(state, addr, diamonds);
    // add balance
    hacd_add(state, addr, &DiamondNumber::from(dias))?;
    Ok(())
}