[package]
name = "field"
version = "0.1.0"
edition = "2024"

[dependencies]
sys = {path = "../sys"}
concat-idents = "1.1.5"
hex = "0.4.3"
base64 = "0.22.1"
base58check = "0.1.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
dyn-clone = "1.0.17"

